name: CI

on:
  push:
    branches: test-setup-elixir
  pull_request:
    branches: develop
env:
  otp-version: '23.1.2'
  elixir-version: '1.11.2'
  MIX_ENV: test

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        otp: ['20.3', '21.3', '22.2', '23.1.2']
        elixir: ['1.11.2']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-elixir@adapt-for-rebar3
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: deps.get
        run: mix deps.get
      - name: compile
        run: mix compile --warnings-as-errors

  format:
    name: Format
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        otp: ['20.3', '21.3', '22.2', '23.1.2']
        elixir: ['1.11.2']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-elixir@adapt-for-rebar3
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: format
        run: mix format --check-formatted

  sobelow:
    name: Sobelow
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        otp: ['20.3', '21.3', '22.2', '23.1.2']
        elixir: ['1.11.2']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-elixir@adapt-for-rebar3
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: format
        run: mix sobelow --skip
  credo:
    name: Credo
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        otp: ['20.3', '21.3', '22.2', '23.1.2']
        elixir: ['1.11.2']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-elixir@adapt-for-rebar3
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: credo
        run: mix credo

  dialyzer:
    needs: build
    name: Dialyzer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        otp: ['21.3', '22.2', '23.1.2']
        elixir: ['1.11.2']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-elixir@adapt-for-rebar3
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{ runner.os }}-erlef-dialyzer-${{ env.otp-version }}-${{ env.elixir-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: dialyze
        run: mix dialyzer

  test:
    needs: build
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        otp: ['21.3', '22.2', '23.1.2']
        elixir: ['1.11.2']
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: paulo-ferraz-oliveira/setup-elixir@adapt-for-rebar3
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: test
        run: mix test
